FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Add a label with your username
LABEL maintainer="praveen10v"

# Copy the requirements file
COPY requirements.txt .

# Install the dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy the application files
COPY . .

# Copy the YOLOv8n weights
COPY yolov8n.pt /app/yolov8n.pt

# Expose the port the app runs on
EXPOSE 5000

# Command to run the application
CMD ["python", "app.py"]
